# Generated by Django 5.1 on 2024-08-26 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_role_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='description',
            new_name='Roles',
        ),
    ]
